# Generated by hand on 2026-03-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("professionals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professional",
            name="contact",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="professional",
            name="social_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
