# Generated by Django 5.2.12 on 2026-03-11 18:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(
                    default=uuid.uuid4, editable=False,
                    primary_key=True, serialize=False
                )),
                ('date', models.DateTimeField()),
                ('status', models.CharField(
                    choices=[
                        ('SCHEDULED', 'Scheduled'),
                        ('COMPLETED', 'Completed'),
                        ('CANCELED', 'Canceled')
                    ],
                    default='SCHEDULED', max_length=20
                )),
                ('professional', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='appointments', to='professionals.professional'
                )),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['date'],
            },
        ),
    ]
